# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:K3Ud47AWeHgqytVvdBAr7vAhj7wkKi47UUYa55MeVsVLao+W8gGTkQ==,iv:czDqJ6i8WpEFGddde32uQdK1iQUtkCKCPJ4HpXqMdCI=,tag:REXxlYiAEhZ81d0m/i1rNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-26T13:51:33Z"
    mac: ENC[AES256_GCM,data:LLO98a6JYxwFU7Gunvp+GAFDbwD1DH1NEZrC4JW+jejHlQMuo2icLA+vF239dUP81DDEsE5xjrhn96QeifbGUPyf5gZPM32fcqzK7lw8a2N1/BP7atdeVLBOSZYwvtYYtTh3NJUwwsFuxH1FmIzKWnyan0EKXULLMTi/R/T86pc=,iv:p8CT2UVfFPjUV3ThdWUyQer6wjU7wYTOAcjCzESwf+I=,tag:DkPpRnqoWT+GEifM2e5XKg==,type:str]
    pgp:
        - created_at: "2021-10-26T13:29:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3kFNbEt6QWKAQ/+IApdcVzw/Tcqshyb/Q+RPFm8bsQs4ErrpdVoksyl1X/O
            wlks2CwVjaQRY3bpXZbhzTwjY7YtLO2SnVrXn6ivLmjX6N6pbhHSQgB6O8lygTkN
            cXg9j16LuPf5fX+mXDPg7W9ujZUhqy03ZIMH2lNUIUpY/bNlH/Jcuo2OSFDlXHVC
            bRcXBX1qx/QByFgWnsFlQfKxGaJCQjzKajGsJxGfaJBcdhWeExgfree4n+my4wph
            qweE11xBItP1qpjauYEiCn4gZhgLv5pEOo7eY1oM866j4iegDyeR7ofOEaDVV43W
            gTVuelk3oX6NmFNt2qsnkAbxBG9+0yxuzCzZqBGGcxYmNGz3Y0roJgu5bCYzcw91
            y53CHBgY7RBr6M09/VHDYkjslliDCdjJsUpriWqtkeBFTKb4aquavCS2fCGddqh2
            f9K/1pey6b2xdhAzCsNZDJMXgXvqt8TI99VS4hAN/2yPBFVarDXVHBVYKIOXQMxm
            mjFi29sQoqcXgf2Xvlcl358gVZaJUs+qPfHIO4b7Bw61CDkBzlylSGjE6CDf+hP1
            VkXe0fMkILlIPI3bwwOPXwgfg75PiirJZ6WqElUojxUp55M+NwkiDqlg/22hMMUg
            cvnY5l8q1OWuLkpVOLz8bx1uIA7pSag/Aswp/ORatEXDJ6kA1wLelwLiQT25st7S
            XgEh/KPZSIzBnzsJhBxvqYffM4fKxu3i1YtxjJIjEtU3S9b6Rx1m40pro41sujNT
            0IcJGREpaZ+p64+k8sZjm53PzK14fOf6DcHm7FgiIUQhaYHJGPniwOeKUVH6F9Y=
            =Za1k
            -----END PGP MESSAGE-----
          fp: 4481DD50972B86E883A37ECDBC75F73DD884DCFD
        - created_at: "2021-10-26T13:29:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxfnTp6fzfK/AQ/+KFDUG+NPjOUkz+kdwN6DEYKliEdQBkV9zG2jJbKJ96T7
            fncAZbxw3YHguNkTfc7rXLvLp0WX0mEnvXNEOFHI/GdQuFLluSMa+L4L6BZqj9XA
            gwbmJ1Nwm6Hvv6bCiZI4pm0y0+NhVMPRjUCTHirB9ReoyM9tksjjcSCdBul8whz8
            42V1kr6KCn1KMLoepgYm4i7tcfAUqlsoeXnADxebakY6Gjoe6uxh3O+o9mMdJ9SA
            Vfduel0sKJhFd9x3afFVqHRm0tZvsAeCbqnVVEXbrr+9CcED1J3ouPPPJIe1mzYy
            kRUjcTCzXX2l6xXtrE8pgulD3eNLkH1spzDYLRiCdX9jPj3yYnZEHV0M04mZePFE
            F24afKDdE/hv7+vEt5N8d5jpPudoW4x8SLzvCWe0b3FheUHs1p4c5Mye1FTJ+H+F
            Hm3/EH1myT9wUFz2pJFZ2XcbFQnEkGCC/YntC5cN92hAosRdO9APJk2Rz8B6S0+/
            0jneE6abG07VZeaj++IdFiIMj1X84qdwNt0LWpjH5d/8TTzItSoMf2TFsAiZ9NQD
            uTEChHsXAA8veVvTzZsqJ0MLvJ0DZKsmV6L1usTMFoNX1dkQt8jAXxMhSS4ssBcr
            TbU6Py7EeucEwCOj83rIqc8oKcD8uz9hw5QoTU7Tm++AkczzfkjShpdf17mDjlfS
            XgHwhxenON3KY9CGlYQGDQP/PqFfLJMMY40/c9YHsU/HUOE+YtCbZlnyeC0xxC6k
            b5JsajZYlf1ISJNrEhmx8fCHFPY2UTyUK/WGAgQwt9ncHdEVWXltODMWdVgHNVs=
            =jNXS
            -----END PGP MESSAGE-----
          fp: 7CC94DE4819CE6EB754AF76125537F25A94A0D5D
    encrypted_regex: ^(data|stringData|(.*)credentials)$
    version: 3.7.1
