---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - k8s-at-home.yaml
  - metallb.yaml
  - traefik.yaml
  - jetstack.yaml
  - external-dns.yaml
  - authentik.yaml
  - stakater.yaml
