---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  NAS_ADDR: "172.20.11.2"
  NAS_MEDIA_PATH: "/mnt/tank/uncompressed/media"
  METALLB_ARP_RANGE: "172.20.11.240-172.20.11.250"
  SVC_TRAEFIK_ADDR: "172.20.11.240"