
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment


    env:
      TZ: "${TZ}"
      LOG_LEVEL: "info"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search-outline"

          traefik.ingress.kubernetes.io/router.middlewares: "networking-external-auth@kubernetescrd" 
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"    

          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: "true"
          
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "home.${SECRET_DOMAIN}"         
            
        hosts:
          - host: "overseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "overseerr.${SECRET_DOMAIN}"
            secretName: "overseerr.${SECRET_DOMAIN/./-}-tls"           
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        mountPath: /app/config
        existingClaim: overseerr-config-v1
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi

